# Generated by Django 3.2.9 on 2024-11-03 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
